
            fastaFiles: [/tmp/tmpQsmPD9/files/7/b/e/dataset_7be42b54-5eac-4f1d-a6bb-0b85e8f1bd67.dat]
            parseRules:
              identifierParseRule: '>([^\s]*)'
              descriptionParseRule: '>(.*)'
            minUniquePeptides: 0
            minPepLen: 7
            maxPeptideMass: 4600
            calcPeakProperties: False
            writeMzTab: True
            separateLfq: False
            lfqStabilizeLargeRatios: True
            lfqRequireMsms: True
            advancedSiteIntensities: True
            matchBetweenRuns: False
            includeContaminants: False
            quantMode: 0
            restrictProteinQuantification: True
            restrictMods: [Pro5,Pro6]
            useCounterparts: True
            paramGroups:
              - files: ['BSA_min_23.mzXML']
                maxMissedCleavages: 2
                fixedModifications: []
                variableModifications: [Oxidation (M)]
                enzymes: [Trypsin/P]
                enzymeMode: 0
                lcmsRunType: 'Reporter ion MS2'
                reporterMassTolerance: 0.003
                reporterPif: 0.6
                reporterFraction: 0
                reporterBasePeakRatio: 0
                filterPif: False
                isobaricLabels:
                      - ['TMT2plex-Lys126','TMT2plex-Nter126',0.0,0.0,6.7,3.0,True]
                      - ['TMT2plex-Lys127','TMT2plex-Nter127',0.0,0.0,0.0,0.0,True]
              - files: ['BSA_min_22.mzxml']
                maxMissedCleavages: 2
                fixedModifications: []
                variableModifications: []
                enzymes: []
                enzymeMode: 0
                lcmsRunType: 'Reporter ion MS2'
                reporterMassTolerance: 0.003
                reporterPif: 0.8
                reporterFraction: 0
                reporterBasePeakRatio: 0
                filterPif: True
                isobaricLabels:
                    - [iTRAQ4plex-Lys114,iTRAQ4plex-Nter114,0,0,0,0,False]
                    - [iTRAQ4plex-Lys115,iTRAQ4plex-Nter115,0,0,0,0,False]
                    - [iTRAQ4plex-Lys116,iTRAQ4plex-Nter116,0,0,0,0,False]
                    - [iTRAQ4plex-Lys117,iTRAQ4plex-Nter117,0,0,0,0,False]
        